update cm-nightly script

diff --git a/android/cm-nightly b/android/cm-nightly
--- a/android/cm-nightly
+++ b/android/cm-nightly
@@ -1,164 +1,79 @@
-#!/system/bin/sh
-#
-# Automatically downloads latest CyanogenMod nightly builds for any CM-supported device
-# nathanForbes
-#
+#!/system/xbin/bash
 
-URL="http://mirror.kanged.net/cm/nightly"
+workdir="$EXTERNAL_STORAGE/cm-nightly.d"
 
-SD_DIR="/sdcard/nightly.p"
-INDEX="${SD_DIR}/index.html"
-TEMP="${SD_DIR}/nightly-index.tmp"
-
-DATE=`date +%m%d%Y`   					# today
-TOMORROW=$((`date +%d`+1))				# add 1 to the day of month integer
-TOMORROW_DATE="`date +%m`${TOMORROW}`date +%Y`"		# insert the $TOMORROW var into full date
-
-READER_FRIENDLY_DATE=`date +%m/%d/%Y`
-READER_FRIENDLY_TOMORROW_DATE="`date +%m`/${TOMORROW}/`date +%Y`"
-
-today()
+msg() { local msg=$1 ; shift ; echo "==> $msg" ; }
+err() 
 {
-	TODAY_INDEXED=`cat ${TEMP} | grep "cm_${1}-${DATE}" | awk '{print $1}'`
-
-	if [ ! -f "/sdcard/${TODAY_INDEXED}" ]
-	then
-		echo "CyanogenMod nightly for ${1}-${READER_FRIENDLY_DATE} found!"
-		echo -n "Proceed with download now? (y/n): "
-		read PROCEED2
-		case "${PROCEED2}" in
-			y|Y|yes|YES)
-				echo "Attempting download, please wait..."
-				cd /sdcard
-				wget ${URL}/${1}/${TODAY_INDEXED}
-				if [ "$?" -ne 0 ]
-				then
-					echo "Download failed!"
-					rm -rf ${TODAY_INDEXED} ${SD_DIR}; exit 1
-				else
-					echo "New ${1}-${READER_FRIENDLY_DATE} nightly located at:"
-					echo "	/sdcard/${TODAY_INDEXED}"
-				fi
-				;;
-			n|no|N|NO)
-				echo "Not downloading ${1}-${READER_FRIENDLY_DATE} nightly at this time..."
-				;;
-			*)
-				echo "'${PROCEED2}' not recognized...try again"
-				rm -rf ${SD_DIR}; exit 1
-				;;
-		esac
-	else
-		echo "${1}-${TODAY_INDEXED} already exists in /sdcard!"
-		rm -rf ${SD_DIR}; exit 1
-	fi
-	return
+  local err=$1 ; shift
+  echo "==> ERROR: $err"
+  rm -rf $workdir
+  exit 1 
 }
 
-tomorrow()
+parseNightly()
 {
-	TOMORROW_INDEXED=`cat ${TEMP} | grep "cm_${1}-${TOMORROW_DATE}" | awk '{print $1}'`
-
-	if [ ! -f "/sdcard/${TOMORROW_INDEXED}" ]
-	then
-		echo "New CyanogenMod nightly for ${1}-${READER_FRIENDLY_TOMORROW_DATE} found!"
-		echo -n "Proceed with download now? (y/n): "
-		read PROCEED
-		case "${PROCEED}" in
-			y|Y|yes|YES)
-				echo "Attempting download, please wait..."
-				cd /sdcard
-				wget ${URL}/${1}/${TOMORROW_INDEXED}
-				if [ "$?" -ne 0 ]
-				then
-					echo "Download failed!"
-					rm -rf ${TOMORROW_INDEXED} ${SD_DIR}; exit 1
-				else
-					echo "New ${1}-${READER_FRIENDLY_TOMORROW_DATE} nightly located at:"
-					echo "	/sdcard/${TOMORROW_INDEXED}"
-				fi
-				;;
-			n|N|no|NO)
-				echo "Not downloading ${1}-${READER_FRIENDLY_TOMORROW_DATE} nightly at this time..."
-				;;
-			*)
-				echo "'${PROCEED}' not recognized, try again..."
-				rm -rf ${SD_DIR}; exit 1
-				;;
-		esac
-	else
-		echo "${1}-${TOMORROW_INDEXED} already exists in /sdcard!"
-		rm -rf ${SD_DIR}; exit 1
-	fi
-	return
+  local device=$1
+  local url="http://mirror.teamdouche.net/?device=${device}"
+  [[ ! "$EXTERNAL_STORAGE" ]] && err "Could not detect External Storage location"
+  [[ -d "$workdir" ]] && rm -rf $workdir
+  mkdir $workdir
+  msg "Working... Please wait"
+  wget -q $url -O $workdir/index
+  [[ "$?" -eq 0 ]] || err "Problem parsing URL"
+  local index="$workdir/index"
+  local temp="$workdir/tmp.files"
+  awk -F'[<>]' '{for(x=1;x<=NF;x++) if($x ~ /.zip$/) print $x}' $index > $temp
+  local pattern="cm_${device}_full"
+  local zip
+  local buildno
+  local builds=()
+  for zip in $( grep "$pattern" $temp )
+  do
+    buildno=$( echo "$zip" | tr "-" " " | awk '{print $2}' | tr "." " " | awk '{print $1}' )
+    builds[$[${#builds[@]}+1]]=$buildno
+  done
+  local num
+  local file
+  for num in ${builds[@]}
+  do
+    if [ ! -f "$EXTERNAL_STORAGE/$pattern-$num.zip" ]
+    then
+      msg "\`$pattern-$num.zip' is available"
+      echo -n "-> Download now? "
+      read download
+      case "$download" in
+        Y*|y*) file="$pattern-$num.zip"; break ; ;;
+      esac
+    else
+      msg "\`$pattern-$num.zip' exists on $EXTERNAL_STORAGE"
+      echo -n "-> Continue with next most recent? "
+      read cont
+      case "$cont" in
+        N*|n*) break ;;
+      esac
+    fi
+  done
+  if [ ! "$file" ]
+  then
+    msg "Not downloading any nightlies..."
+  else
+    local nightlyDownload="http://mirror.teamdouche.net/get/${device}/${file}"
+    msg "Attempting download..."
+    wget $nightlyDownload -O $EXTERNAL_STORAGE/$file
+    [[ "$?" -eq 0 ]] || err "Error occurred with download"
+  fi
 }
 
-parse_nightly()
-{
-	echo "Working, please wait..."
+device=$( getprop ro.product.device )
 
-	mkdir -p ${SD_DIR}; cd ${SD_DIR};
-	rm -rf ${INDEX} ${TEMP}
-	wget -q ${URL}/${1}/
-
-	if [ "$?" -eq 0 ]
-	then
-		if [ -e "${INDEX}" ]
-		then
-			awk -F'[<>]' '{for(x=1;x<=NF;x++) if($x ~ /.zip$/) print $x}' ${INDEX} >${TEMP}
-
-			if [ -e "${TEMP}" ]; then rm -rf ${INDEX}; fi;
-		else
-			echo "Error parsing!"
-			cd ..; rm -rf ${SD_DIR}; exit 1
-		fi
-	else
-		echo "Error parsing!"
-		cd ..; rm -rf ${SD_DIR}; exit 1
-	fi
-
-	if [ "`cat ${TEMP} | grep "cm_${1}-${TOMORROW_DATE}" | awk '{print $1}'`" != "" ]
-	then
-		tomorrow ${1}
-	else
-		if [ "`cat ${TEMP} | grep "cm_${1}-${DATE}" | awk '{print $1}'`" != "" ]
-		then
-			echo "No nightly found for ${1}-${READER_FRIENDLY_TOMORROW_DATE}, (tomorrow)..."
-			echo -n "Try today's date instead? (y/n): "
-			read TODAY
-			case "${TODAY}" in
-				y|Y|yes|YES)
-					today ${1}
-					;;
-				n|N|no|NO)
-					echo "Not checking for new nightly for today on ${READER_FRIENDLY_DATE}"
-					;;
-				*)
-					echo "'${TODAY}' not recognized, try again..."
-					rm -rf ${SD_DIR}; exit 1
-					;;
-			esac
-		else
-			echo "No ${1}-${READER_FRIENDLY_DATE} found. Please wait for a newer nightly"
-		fi
-	fi
-	return
-}
-
-
-DEVICE=`getprop ro.product.device`
-
-case "${DEVICE}" in
-
-	bravo|expresso|hero|heroc|inc|liberty|passion|sholes|supersonic) parse_nightly ${DEVICE}
-					;;
-			dream|sapphire) parse_nightly dream_sapphire
-					;;
-	     			     *) echo "${DEVICE} not currently supported"
-					;;
-
+case "$device" in
+  bravo|expresso|hero|heroc|inc|liberty|legend|passion|sholes|supersonic)
+    parseNightly $device ;;
+  dream|sapphire)
+    parseNightly dream_sapphire ;;
+  *)
+    err "\`$device' not supported" ;;
 esac
 
-rm -rf ${SD_DIR}
-
-exit 0
+rm -rf $workdir
